### ISSUE TITLE
Fix the server error

### ISSUE THREAD

**Issue by masakudamatsu** [masakudamatsu/luminance-picker#87]
Issue #85 causes a server error as follows:
```
Error:
Invalid `prisma.rgbColorCodes.findMany()` invocation in
/Users/kudamatsu/projects/luminance-picker/server/src/resolvers/Query.js:27:53

  Invalid feature flag: aggregations
    at PrismaClientFetcher.request (/Users/kudamatsu/projects/luminance-picker/server/node_modules/@prisma/client/runtime/index.js:1:211418)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The only thing we've changed is the database. 

We first check if the error can be reproduced with a subset (first 100 observationis) of the database. If it does, we will write a bug report to Prisma by following this guideline:
https://www.prisma.io/docs/more/creating-bug-reports

**Comment by masakudamatsu** [comment]
We do replicate the error with a small subset of the database.

**Comment by masakudamatsu** [comment]
According to: https://github.com/prisma/prisma/issues/3659
Prisma has released version 2.6 on 1 Sept and its primary update is `prisma introspect`. 

We'll try to install version 2.6 and see if we replicate the error.

**Comment by masakudamatsu** [comment]
We've installed the latest version (2.8.0) and still get the same error...

**Comment by masakudamatsu** [comment]
We've minimized the code to replicate the error. Then download the code as Zip and extract it and `npm install`. Then we cannot replicate the error anymore...

Maybe we should uninstall Prisma first and then reinstall it.

**Comment by masakudamatsu** [comment]
We clone the repo, edit `package.json` to change Prisma CLI version to 2.8.0, and execute `npm install` to install Prisma CLI from scratch. The error disappears!
